checks:
  python: true

build:
  nodes:
    analysis:
      dependencies:
        override:
          - pip install -r requirements.txt
      tests:
        override:
          - py-scrutinizer-run
          -
            command: pylint-run
            use_website_config: false

    tests: true
filter:
  excluded_paths:
    - '*/test/*'
    - 'core-models/ocrd_models/model/ocrd_page_generateds.py'
  dependency_paths:
    - 'lib/*'
