checks:
  python: true

build:
  nodes:
    analysis:
      dependencies:
        override:
          - make deps-ubuntu
          - make install
      tests:
        override:
          - py-scrutinizer-run
          -
            command: pylint-run
            use_website_config: false
    tests:
      tests:
        override:
          - true
filter:
  excluded_paths:
    - 'tests/*'
    - 'ocrd_models/ocrd_models/ocrd_page_generateds.py'
  dependency_paths:
    - 'lib/*'
