checks:
  python: true

build:
  image: default-bionic
  environment:
    python:
      version: 3.8.2
      virtualenv: true
    variables:
      DEBIAN_FRONTEND: noninteractive
  nodes:
    analysis:
      dependencies:
        override:
          - command: sudo make deps-ubuntu
            idle_timeout: 600
          - make install
      tests:
        override:
          - py-scrutinizer-run
          -
            command: pylint-run
            use_website_config: false
    tests:
      tests:
        override:
          - true
filter:
  excluded_paths:
    - 'tests/*'
    - 'ocrd_models/ocrd_models/ocrd_page_generateds.py'
  dependency_paths:
    - 'lib/*'
