ARG BASE_IMAGE=docker.io/ocrd/core-cuda
FROM $BASE_IMAGE AS ocrd_core_base

WORKDIR /build

COPY Makefile .

RUN make deps-torch
# Smoke Test
RUN ocrd --version

WORKDIR /data

CMD ["/usr/local/bin/ocrd", "--help"]

