openapi: 3.0.0
servers:
  - url: 'http://docr.kba.cloud:8765/'
info:
  version: 0.0.1
  title: OCR-D HTTP API
  description: This is a definition of the modules used for the OCR-D project.
  contact:
    email: volker.hartmann@kit.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Bildvorverarbeitung
    description: >
      Verfahren, die die Digitalisate für die Layout- und Texterkennung
      charakterisieren und optimieren.
  - name: Layouterkennung
    description: >
      Die Erfassung des korrekten, d.h. die Wiedergabe des logisch strukturell
      auf sich beziehenden Textflusses und hohe Textgenauigkeit.
  - name: Textoptimierung
    description: >
      Kombination mehrere OCR-Engines mit anschließender Nachkorrektur zur
      Verbesserung der Textergebnisse.
  - name: Modellbildung
    description: >
      Training der Modelle und Bereitstellung dieser.
  - name: Langzeitarchivierung
    description: >
      Sicherung der Langzeitverfügbarkeit und Referenzierbarkeit der gewonnenen
      Texte.
  - name: Qualitätssicherung
    description: >
      Bestimmung/Schätzung des Potenzials der einzelnen Komponenten.
paths: {}
components:
  headers: {}
  schemas: {}
