message_queue:
  address: localhost
  port: 5672
  credentials:
    username: admin
    password: admin
  ssh:
    username: mm
    path_to_privkey: /home/mm/.ssh/cloud.key
mongo_db:
  address: localhost
  port: 27018
  credentials:
    username: admin
    password: admin
  ssh:
    username: mm
    path_to_privkey: /home/mm/.ssh/cloud.key
hosts:
  - address: localhost
    username: mm
    path_to_privkey: /home/mm/.ssh/cloud.key
    deploy_processors:
      - name: ocrd-cis-ocropy-binarize
        number_of_instance: 1
        deploy_type: native
  - address: localhost
    username: mm
    path_to_privkey: /home/mm/.ssh/cloud.key
    deploy_processors:
      - name: ocrd-gibt-es-nicht-test
        number_of_instance: 1
        deploy_type: docker
