name: Run ocrd network integration tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        os:
          - ubuntu-22.04
          - macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu"* ]];then
            sudo apt-get -y update
            sudo make deps-ubuntu
          else
            HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 \
            HOMEBREW_NO_AUTO_UPDATE=1 \
            brew install imagemagick geos bash  # opencv
          fi
          make install deps-test
      - name: Install Docker on macOS
        if: runner.os == 'macos'
        run: |
          brew install docker docker-compose
          colima start
      - name: Test network integration with pytest
        run: |
          if [[ "${{ matrix.os }}" == "macos"* ]];then
            make integration-test DOCKER_COMPOSE=docker-compose
          else
            make integration-test
          fi
